replicaCount: 2

image: 
  repository: ghcr.io/alexandermamaniy/kubernetes-cicd
  tag: c645c9379dc1e786c21542d3d0bbf773cee00a4c
  pullPolicy: IfNotPresent
  imagePullSecrets: ghcr-secret

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi